// import Accordion from "efsane-accordion";
// import Button from "efsane-button";
// import ButtonGroup from "efsane-button-group";
// import Card from "efsane-card";
// import Checkbox from "efsane-checkbox";
// import ColorPicker from "efsane-color-picker";
// import Datepicker from "efsane-datepicker";
// import DatetimePicker from "efsane-datetime-picker";
// import Dialog from "efsane-dialog";
// import DocumentUpload from "efsane-document-upload";
// import Fieldset from "efsane-fieldset";
// import Footer from "efsane-footer";
// import Form from "efsane-form";
// import ImageUpload from "efsane-image-upload";
// import Input from "efsane-input";
// import Modal from "efsane-modal";
// import Navbar from "efsane-navbar";
// import Notification from "efsane-notification";
// import ProgressBar from "efsane-progress-bar";
// import Radio from "efsane-radio";
// import Range from "efsane-range";
// import Select from "efsane-select";
// import SelectSearch from "efsane-select-search";
// import Sidebar from "efsane-sidebar";
// import Spinner from "efsane-spinner";
// import Switch from "efsane-switch";
// import Table from "efsane-table";
// import Tabs from "efsane-tabs";
// import TextArea from "efsane-text-area";

export const registerPublishOwnPackages = {
  install() {
    // app.component("efsane-input-local", Input);
    // app.component("efsane-accordion-local", Accordion);
    // app.component("efsane-button-local", Button);
    // app.component("efsane-button-group-local", ButtonGroup);
    // app.component("efsane-card-local", Card);
    // app.component("efsane-checkbox-local", Checkbox);
    // app.component("efsane-color-picker-local", ColorPicker);
    // app.component("efsane-datepicker-local", Datepicker);
    // app.component("efsane-datetime-picker-local", DatetimePicker);
    // app.component("efsane-dialog-local", Dialog);
    // app.component("efsane-document-upload-local", DocumentUpload);
    // app.component("efsane-fieldset-local", Fieldset);
    // app.component("efsane-footer-local", Footer);
    // app.component("efsane-form-local", Form);
    // app.component("efsane-image-upload-local", ImageUpload);
    // app.component("efsane-input-local", Input);
    // app.component("efsane-modal-local", Modal);
    // app.component("efsane-navbar-local", Navbar);
    // app.component("efsane-notification-local", Notification);
    // app.component("efsane-progress-bar-local", ProgressBar);
    // app.component("efsane-radio-local", Radio);
    // app.component("efsane-range-local", Range);
    // app.component("efsane-select-local", Select);
    // app.component("efsane-select-search-local", SelectSearch);
    // app.component("efsane-sidebar-local", Sidebar);
    // app.component("efsane-spinner-local", Spinner);
    // app.component("efsane-switch-local", Switch);
    // app.component("efsane-table-local", Table);
    // app.component("efsane-tabs-local", Tabs);
    // app.component("efsane-text-area-local", TextArea);
  },
};
