// import Accordion from "efsane-accordion";
// import Button from "efsane-button";
// import ButtonGroup from "efsane-button-group";
// import Card from "efsane-card";
// import Checkbox from "efsane-checkbox";
// import ColorPicker from "efsane-color-picker";
// import Datepicker from "efsane-datepicker";
// import DatetimePicker from "efsane-datetime-picker";
// import Dialog from "efsane-dialog";
// import DocumentUpload from "efsane-document-upload";
// import Fieldset from "efsane-fieldset";
// import Footer from "efsane-footer";
// import Form from "efsane-form";
// import ImageUpload from "efsane-image-upload";
// import Input from "efsane-input";
// import Modal from "efsane-modal";
// import Navbar from "efsane-navbar";
// import Notification from "efsane-notification";
// import ProgressBar from "efsane-progress-bar";
// import Radio from "efsane-radio";
// import Range from "efsane-range";
// import Select from "efsane-select";
// import SelectSearch from "efsane-select-search";
// import Sidebar from "efsane-sidebar";
// import Spinner from "efsane-spinner";
// import Switch from "efsane-switch";
// import Table from "efsane-table";
// import Tabs from "efsane-tabs";
// import TextArea from "efsane-text-area";
// import TextArea from "efsane-layout";

export const registerPublishOwnPackages = {
  install() {
    // app.component("efsane-input", Input);
    // app.component("efsane-accordion", Accordion);
    // app.component("efsane-button", Button);
    // app.component("efsane-button-group", ButtonGroup);
    // app.component("efsane-card", Card);
    // app.component("efsane-checkbox", Checkbox);
    // app.component("efsane-color-picker", ColorPicker);
    // app.component("efsane-datepicker", Datepicker);
    // app.component("efsane-datetime-picker", DatetimePicker);
    // app.component("efsane-dialog", Dialog);
    // app.component("efsane-document-upload", DocumentUpload);
    // app.component("efsane-fieldset", Fieldset);
    // app.component("efsane-footer", Footer);
    // app.component("efsane-form", Form);
    // app.component("efsane-image-upload", ImageUpload);
    // app.component("efsane-input", Input);
    // app.component("efsane-modal", Modal);
    // app.component("efsane-navbar", Navbar);
    // app.component("efsane-notification", Notification);
    // app.component("efsane-progress-bar", ProgressBar);
    // app.component("efsane-radio", Radio);
    // app.component("efsane-range", Range);
    // app.component("efsane-select", Select);
    // app.component("efsane-select-search", SelectSearch);
    // app.component("efsane-sidebar", Sidebar);
    // app.component("efsane-spinner", Spinner);
    // app.component("efsane-switch", Switch);
    // app.component("efsane-table", Table);
    // app.component("efsane-tabs", Tabs);
    // app.component("efsane-text-area", TextArea);
    // app.component("efsane-layout", Layout);
  },
};
